import { GameLevel, HighwayMap, TrackTheme, TrackThemeId, VehicleConfig } from '../types/game';

import bikeNinjaThumb from '../assets/images/red_superbike_thumb_1790481842307.jpg';
import carPhantomThumb from '../assets/images/red_supercar_thumb_1790481852581.jpg';
import bikeHayabusaThumb from '../assets/images/hayabusa_bike_thumb_1790482609451.jpg';
import bikeHarleyThumb from '../assets/images/harley_cruiser_thumb_1790482619834.jpg';
import carHypercarThumb from '../assets/images/hypercar_blue_thumb_1790482595232.jpg';
import carPoliceThumb from '../assets/images/police_interceptor_thumb_1790482631255.jpg';

export const VEHICLES: VehicleConfig[] = [
  // --- BIKES ---
  {
    id: 'bike',
    name: 'Ninja 900 ZX',
    category: 'Bike',
    tagline: 'Razor-sharp agility & slim profile',
    description: 'Slips between heavy trucks with ease. High top speed and tiny collision zone.',
    width: 26,
    height: 60,
    color: '#10b981', // Emerald green
    accentColor: '#047857',
    topSpeed: 210,
    acceleration: 9.5,
    handling: 9.8,
    hitboxScale: 0.72,
    icon: '🏍️',
    image: bikeNinjaThumb,
    price: 0,
    unlocked: true,
  },
  {
    id: 'caferacer',
    name: 'Hayabusa 1300R',
    category: 'Bike',
    tagline: 'Aerodynamic Hyperbike Bullet',
    description: 'Blistering acceleration with streamlined aerodynamics for record-breaking speed runs.',
    width: 27,
    height: 62,
    color: '#f97316', // Orange
    accentColor: '#c2410c',
    topSpeed: 245,
    acceleration: 9.8,
    handling: 9.2,
    hitboxScale: 0.74,
    icon: '⚡',
    image: bikeHayabusaThumb,
    price: 2500,
    unlocked: true,
  },
  {
    id: 'harley',
    name: 'Harley Thunder V-Twin',
    category: 'Bike',
    tagline: 'Heavy Chopper & Rumble Exhaust',
    description: 'Massive stability, wide magnetic coin pull radius, and powerful steady cruise.',
    width: 30,
    height: 66,
    color: '#eab308', // Chrome gold
    accentColor: '#a16207',
    topSpeed: 195,
    acceleration: 8.4,
    handling: 8.2,
    hitboxScale: 0.76,
    icon: '🔥',
    image: bikeHarleyThumb,
    price: 3500,
    unlocked: true,
  },

  // --- CARS ---
  {
    id: 'car',
    name: 'Phantom GT-R',
    category: 'Car',
    tagline: 'Twin-turbo aerodynamic supercar',
    description: 'Maximum stability, prolonged nitro boost, and dynamic downforce for high speeds.',
    width: 38,
    height: 72,
    color: '#ef4444', // Crimson red
    accentColor: '#b91c1c',
    topSpeed: 230,
    acceleration: 8.8,
    handling: 8.5,
    hitboxScale: 0.85,
    icon: '🏎️',
    image: carPhantomThumb,
    price: 0,
    unlocked: true,
  },
  {
    id: 'hypercar',
    name: 'Bugatti Apex V16',
    category: 'Car',
    tagline: '1600 HP Apex Hypercar',
    description: 'The ultimate king of the highway. Insane top speeds, rapid turbo charge, and carbon chassis.',
    width: 39,
    height: 74,
    color: '#0284c7', // Sky blue
    accentColor: '#0369a1',
    topSpeed: 265,
    acceleration: 9.9,
    handling: 9.0,
    hitboxScale: 0.86,
    icon: '🚀',
    image: carHypercarThumb,
    price: 5000,
    unlocked: true,
  },
  {
    id: 'police',
    name: 'Interceptor Pursuit',
    category: 'Car',
    tagline: 'High-speed Highway Police Cruiser',
    description: 'Flashing LED strobes, armored heavy front bumper, and siren bonus scoring.',
    width: 40,
    height: 75,
    color: '#3b82f6', // Police blue
    accentColor: '#1d4ed8',
    topSpeed: 240,
    acceleration: 9.0,
    handling: 8.8,
    hitboxScale: 0.88,
    icon: '🚔',
    image: carPoliceThumb,
    price: 4000,
    unlocked: true,
  },
  {
    id: 'muscle',
    name: 'V8 Road Hammer',
    category: 'Car',
    tagline: 'Heavy American Muscle brute',
    description: 'High durability, bonus magnetic attraction for coins, and roaring exhaust power.',
    width: 40,
    height: 76,
    color: '#f59e0b', // Amber/gold
    accentColor: '#b45309',
    topSpeed: 215,
    acceleration: 8.2,
    handling: 7.8,
    hitboxScale: 0.88,
    icon: '🚗',
    price: 2000,
    unlocked: true,
  },
];

export const TRACK_THEMES: Record<TrackThemeId, TrackTheme> = {
  sunset: {
    id: 'sunset',
    name: 'Sunset Highway',
    skyColor: '#1e112a', // Sunset purple-dark
    roadColor: '#18181b', // Zinc 900
    stripeColor: '#fbbf24', // Amber marks
    shoulderColor: '#27272a',
    ambientColor: '#f97316',
    hazardColor: '#ef4444',
  },
  desert: {
    id: 'desert',
    name: 'Golden Dune Highway',
    skyColor: '#451a03',
    roadColor: '#262626',
    stripeColor: '#fbbf24', // Yellow road marks
    shoulderColor: '#78350f',
    ambientColor: '#d97706',
    hazardColor: '#ef4444',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber City Expressway',
    skyColor: '#020617', // Slate 950
    roadColor: '#0f172a', // Slate 900
    stripeColor: '#38bdf8', // Neon cyan road marks
    shoulderColor: '#1e293b', // Slate 800
    ambientColor: '#0284c7',
    hazardColor: '#f43f5e',
  },
  storm: {
    id: 'storm',
    name: 'Midnight Monsoon',
    skyColor: '#090d16',
    roadColor: '#0b1120',
    stripeColor: '#cbd5e1',
    shoulderColor: '#1e293b',
    ambientColor: '#6366f1',
    hazardColor: '#ec4899',
  },
  tokyo: {
    id: 'tokyo',
    name: 'Tokyo Night Expressway',
    skyColor: '#0f051d',
    roadColor: '#13111c',
    stripeColor: '#ec4899', // Pink neon stripes
    shoulderColor: '#1f1a2e',
    ambientColor: '#a855f7',
    hazardColor: '#ef4444',
  },
  snow: {
    id: 'snow',
    name: 'Alpine Frost Expressway',
    skyColor: '#0c1a2e',
    roadColor: '#1e293b',
    stripeColor: '#e0f2fe',
    shoulderColor: '#cbd5e1',
    ambientColor: '#38bdf8',
    hazardColor: '#f43f5e',
  },
  volcano: {
    id: 'volcano',
    name: 'Magma Ridge Valley',
    skyColor: '#450a0a',
    roadColor: '#18181b',
    stripeColor: '#f97316',
    shoulderColor: '#7f1d1d',
    ambientColor: '#ef4444',
    hazardColor: '#fbbf24',
  },
  coastal: {
    id: 'coastal',
    name: 'Pacific Coast Highway',
    skyColor: '#082f49',
    roadColor: '#0f172a',
    stripeColor: '#38bdf8',
    shoulderColor: '#0369a1',
    ambientColor: '#06b6d4',
    hazardColor: '#f43f5e',
  },
  neon_valley: {
    id: 'neon_valley',
    name: 'Synthwave Sunset Grid',
    skyColor: '#2e1065',
    roadColor: '#170f2b',
    stripeColor: '#f43f5e',
    shoulderColor: '#3b0764',
    ambientColor: '#d946ef',
    hazardColor: '#fbbf24',
  },
  hyperway: {
    id: 'hyperway',
    name: 'Apex Orbital Hyperway',
    skyColor: '#030712',
    roadColor: '#020617',
    stripeColor: '#a855f7',
    shoulderColor: '#111827',
    ambientColor: '#8b5cf6',
    hazardColor: '#ef4444',
  },
};

export const HIGHWAY_MAPS: HighwayMap[] = [
  {
    id: 'sunset',
    name: 'Sunset Highway',
    subtitle: 'Golden hour cruising along the coastal highway',
    icon: '🌅',
    badge: 'CLASSIC',
    weather: 'Warm Sunset & Clear Skies',
  },
  {
    id: 'desert',
    name: 'Golden Dune Desert',
    subtitle: 'Scorching desert sands and amber asphalt',
    icon: '🏜️',
    badge: 'DESERT RUN',
    weather: 'High Heat & Sand Haze',
  },
  {
    id: 'cyber',
    name: 'Cyber City Expressway',
    subtitle: 'Futuristic highway glowing with cyan neon skyway',
    icon: '🏙️',
    badge: 'CYBERPUNK',
    weather: 'Neon Night & Clear Visibility',
  },
  {
    id: 'storm',
    name: 'Midnight Monsoon',
    subtitle: 'Heavy rain, dark wet asphalt and lightning flashes',
    icon: '⛈️',
    badge: 'WET TRACK',
    weather: 'Heavy Rain & Thunder',
  },
  {
    id: 'tokyo',
    name: 'Tokyo Night Expressway',
    subtitle: 'High-speed metropolitan loop with neon pink vibes',
    icon: '🗼',
    badge: 'MIDNIGHT',
    weather: 'Tokyo Night & City Lights',
  },
  {
    id: 'snow',
    name: 'Alpine Frostway',
    subtitle: 'Freezing mountain pass on slick icy asphalt',
    icon: '❄️',
    badge: 'COLD PASS',
    weather: 'Freezing Frost & Snow Fall',
  },
  {
    id: 'coastal',
    name: 'Pacific Coast Highway',
    subtitle: 'Ocean breeze high-speed sweepers and cliff views',
    icon: '🌊',
    badge: 'SCENIC',
    weather: 'Pacific Breeze & Blue Sky',
  },
  {
    id: 'volcano',
    name: 'Magma Ridge Valley',
    subtitle: 'Scorching red rock canyon with raging volcanic heat',
    icon: '🌋',
    badge: 'MAGMA',
    weather: 'Lava Heat & Glowing Embers',
  },
  {
    id: 'neon_valley',
    name: 'Synthwave Sunset Grid',
    subtitle: '80s retro grid run with magenta neon twilight',
    icon: '🌆',
    badge: 'SYNTHWAVE',
    weather: 'Retro Sunset Grid',
  },
  {
    id: 'hyperway',
    name: 'Apex Orbital Hyperway',
    subtitle: 'Cosmic deep-space speedway with violet stars',
    icon: '🌌',
    badge: 'HYPERWAY',
    weather: 'Deep Space & Cosmic Nebula',
  },
];

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 1,
    name: 'Level 1: Sunset Highway',
    subtitle: 'Golden hour cruising and traffic dodging',
    themeId: 'sunset',
    targetDistance: 1200,
    targetScore: 4000,
    rewardCoins: 500,
    rewardDiamonds: 10,
    unlocked: true,
    stars: 3,
    icon: '🌅',
    badge: 'BEGINNER',
  },
  {
    id: 2,
    name: 'Level 2: Desert Dunes',
    subtitle: 'High-speed run on sun-scorched sandway',
    themeId: 'desert',
    targetDistance: 2000,
    targetScore: 8000,
    rewardCoins: 800,
    rewardDiamonds: 15,
    unlocked: true,
    stars: 2,
    icon: '🏜️',
    badge: 'AMATEUR',
  },
  {
    id: 3,
    name: 'Level 3: Cyber Neon City',
    subtitle: 'Futuristic expressway with neon light trails',
    themeId: 'cyber',
    targetDistance: 3000,
    targetScore: 14000,
    rewardCoins: 1200,
    rewardDiamonds: 20,
    unlocked: true,
    stars: 1,
    icon: '🏙️',
    badge: 'PRO RACER',
  },
  {
    id: 4,
    name: 'Level 4: Midnight Monsoon',
    subtitle: 'Torrential rain storm & wet slick road',
    themeId: 'storm',
    targetDistance: 4000,
    targetScore: 22000,
    rewardCoins: 1600,
    rewardDiamonds: 25,
    unlocked: true,
    stars: 0,
    icon: '⛈️',
    badge: 'VETERAN',
  },
  {
    id: 5,
    name: 'Level 5: Tokyo Expressway',
    subtitle: 'Dense heavy traffic blitz and tight overtakes',
    themeId: 'tokyo',
    targetDistance: 5000,
    targetScore: 32000,
    rewardCoins: 2000,
    rewardDiamonds: 30,
    unlocked: true,
    stars: 0,
    icon: '🗼',
    badge: 'EXPERT',
  },
  {
    id: 6,
    name: 'Level 6: Alpine Frostway',
    subtitle: 'Freezing mountain pass with slick cold asphalt',
    themeId: 'snow',
    targetDistance: 6200,
    targetScore: 42000,
    rewardCoins: 2500,
    rewardDiamonds: 35,
    unlocked: true,
    stars: 0,
    icon: '❄️',
    badge: 'FROST RACER',
  },
  {
    id: 7,
    name: 'Level 7: Pacific Coast Highway',
    subtitle: 'Ocean breeze high-speed sweepers and scenic cliffs',
    themeId: 'coastal',
    targetDistance: 7500,
    targetScore: 54000,
    rewardCoins: 3000,
    rewardDiamonds: 40,
    unlocked: false,
    stars: 0,
    icon: '🌊',
    badge: 'COASTAL ACE',
  },
  {
    id: 8,
    name: 'Level 8: Magma Ridge Canyon',
    subtitle: 'Scorching red rock canyon with raging heat',
    themeId: 'volcano',
    targetDistance: 9000,
    targetScore: 68000,
    rewardCoins: 3800,
    rewardDiamonds: 50,
    unlocked: false,
    stars: 0,
    icon: '🌋',
    badge: 'FIRE DRIVER',
  },
  {
    id: 9,
    name: 'Level 9: Synthwave Sunset Grid',
    subtitle: '80s Retro grid speedrun with hot pink neon reflections',
    themeId: 'neon_valley',
    targetDistance: 10500,
    targetScore: 82000,
    rewardCoins: 4500,
    rewardDiamonds: 60,
    unlocked: false,
    stars: 0,
    icon: '🌆',
    badge: 'SYNTH RUNNER',
  },
  {
    id: 10,
    name: 'Level 10: Thunderstorm Gorge',
    subtitle: 'Lightning flashes illuminating intense 4-lane gridlock',
    themeId: 'storm',
    targetDistance: 12000,
    targetScore: 98000,
    rewardCoins: 5500,
    rewardDiamonds: 75,
    unlocked: false,
    stars: 0,
    icon: '⚡',
    badge: 'THUNDER KING',
  },
  {
    id: 11,
    name: 'Level 11: Tokyo Midnight Blitz',
    subtitle: 'Extreme top-speed convoy chase through downtown Tokyo',
    themeId: 'tokyo',
    targetDistance: 13500,
    targetScore: 115000,
    rewardCoins: 7000,
    rewardDiamonds: 90,
    unlocked: false,
    stars: 0,
    icon: '🏎️',
    badge: 'GRAND MASTER',
  },
  {
    id: 12,
    name: 'Level 12: Apex Infinity Hyperway',
    subtitle: 'The ultimate endless speed trial for true road legends',
    themeId: 'hyperway',
    targetDistance: 15000,
    targetScore: 140000,
    rewardCoins: 10000,
    rewardDiamonds: 120,
    unlocked: false,
    stars: 0,
    icon: '👑',
    badge: 'SUPREME LEGEND',
  },
];
